### PR TITLE
Correct useFirestoreCollection interface

### PR DESCRIPTION
**Pull request by kevinhwang**
### Description

Correct useFirestoreCollection interface

### Code sample

https://codesandbox.io/s/xenodochial-pasteur-o21zn

### CODE REVIEW

**Comment by kevinhwang** [comment]
@jamesdaniels Can you give this guy a review :)

**Comment by dagerikhl** [comment]
Can confirm this fixes the type in my project. Hope this gets reviewed and merged :+1:

**Comment by kevinhwang** [comment]
@jhuleatt Could you review? :)

**Comment by seanaguinaga** [comment]
Yay! <3 Christmas is gonna come early

**Pull request closed without merging**
