### PR TITLE
update firestore generics

### LINKED ISSUE #355: Typings problem: Can't pass record type to `useFirestoreCollection`
When I use `useFirestoreCollection` I always have to use it as `useFirestoreCollection<unknown>` in TypeScript.

Can you please change:
```diff
-export function useFirestoreCollection<T = { [key: string]: unknown }>(
+export function useFirestoreCollection<T = firebase.firestore.DocumentData>(
  query: firebase.firestore.Query,
  options?: ReactFireOptions<T[]>
-): ObservableStatus<T extends {} ? T[] : firebase.firestore.QuerySnapshot> {
+): ObservableStatus<firebase.firestore.QuerySnapshot<T>> {
  const observableId = `firestore:collection:${getUniqueIdForFirestoreQuery(query)}`;
  const observable$ = fromCollectionRef(query);

  return useObservable(observableId, observable$, options);
}
```
here:
https://github.com/FirebaseExtended/reactfire/blob/9d96d92d212fbd616506848180e02e84d4866409/src/firestore.tsx#L110-L118

### PR DESCRIPTION
**Pull request by jhuleatt**
fixes #355

### CODE REVIEW

**Review by jamesdaniels — APPROVED** [review]
LGTM

**Comment by devth** [comment]
This is awesome. Any way to get a new rc published so we can use this fix?

**Comment by jhuleatt** [comment]
Hey @devth yes we're working on another rc, but want to get a few other changes in first (like #372). Until then, you can use:

```shell
npm install reactfire@canary
```

to try out the latest merged PRs!

**Comment by devth** [comment]
@jhuleatt thanks! Looking forward to a new RC 🚀

**Pull request merged**
